#ifndef POTHOLEDETENCTIONSYSTEM_HISTOGRAMELABORATION_H
#define POTHOLEDETENCTIONSYSTEM_HISTOGRAMELABORATION_H

#include <opencv2/core.hpp>

using namespace cv;

Mat ExtractHistograms(Mat src, String candidateName);

#endif //POTHOLEDETENCTIONSYSTEM_HISTOGRAMELABORATION_H
