#ifndef POTHOLEDETECTIONSYSTEM_HISTOGRAMELABORATION_H
#define POTHOLEDETECTIONSYSTEM_HISTOGRAMELABORATION_H

#include <opencv2/core.hpp>

using namespace cv;

Mat ExtractHistograms(Mat src, String candidateName);

#endif //POTHOLEDETECTIONSYSTEM_HISTOGRAMELABORATION_H
